language: cpp

before_install:
  # inspired by https://github.com/d-led/cucumber-cpp-premake/blob/master/.travis.yml
  - sudo add-apt-repository --yes "ppa:codegear/release"

  - sudo apt-get update -qq
  - sudo apt-get -qq --yes install premake4
   
install:
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++

before_script:
  - premake4 gmake

script:
  - make -C build
  - ./CheatEngine/tests/bin/Tests
  - sudo ./CheatEngine/integration/bin/IntegrationTest

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
